jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#debug=true
  jpa:
    database: MYSQL
# 显示后台处理的SQL语句
    show-sql: true
